package cn.xdl.ovls.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import cn.xdl.ovls.entity.Evaluate;

public class EvaluateSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public String insertSelective(Evaluate record) {
        BEGIN();
        INSERT_INTO("evaluate");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUseId() != null) {
            VALUES("use_id", "#{useId,jdbcType=INTEGER}");
        }
        
        if (record.getContext() != null) {
            VALUES("context", "#{context,jdbcType=VARCHAR}");
        }
        
        if (record.getPublishTime() != null) {
            VALUES("publish_time", "#{publishTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getVideoId() != null) {
            VALUES("video_id", "#{videoId,jdbcType=INTEGER}");
        }
        
        if (record.getLikeCount() != null) {
            VALUES("like_count", "#{likeCount,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public String updateByPrimaryKeySelective(Evaluate record) {
        BEGIN();
        UPDATE("evaluate");
        
        if (record.getUseId() != null) {
            SET("use_id = #{useId,jdbcType=INTEGER}");
        }
        
        if (record.getContext() != null) {
            SET("context = #{context,jdbcType=VARCHAR}");
        }
        
        if (record.getPublishTime() != null) {
            SET("publish_time = #{publishTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getVideoId() != null) {
            SET("video_id = #{videoId,jdbcType=INTEGER}");
        }
        
        if (record.getLikeCount() != null) {
            SET("like_count = #{likeCount,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}