package cn.xdl.ovls.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import cn.xdl.ovls.entity.Issue;

public class IssueSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public String insertSelective(Issue record) {
        BEGIN();
        INSERT_INTO("issue");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getHeadline() != null) {
            VALUES("headline", "#{headline,jdbcType=VARCHAR}");
        }
        
        if (record.getIssueContext() != null) {
            VALUES("issue_context", "#{issueContext,jdbcType=VARCHAR}");
        }
        
        if (record.getPublishTime() != null) {
            VALUES("publish_time", "#{publishTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAnswerCount() != null) {
            VALUES("answer_count", "#{answerCount,jdbcType=INTEGER}");
        }
        
        if (record.getBrowseCount() != null) {
            VALUES("browse_count", "#{browseCount,jdbcType=INTEGER}");
        }
        
        if (record.getVideoId() != null) {
            VALUES("video_id", "#{videoId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getRightAnswerId() != null) {
            VALUES("right_answer_id", "#{rightAnswerId,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public String updateByPrimaryKeySelective(Issue record) {
        BEGIN();
        UPDATE("issue");
        
        if (record.getHeadline() != null) {
            SET("headline = #{headline,jdbcType=VARCHAR}");
        }
        
        if (record.getIssueContext() != null) {
            SET("issue_context = #{issueContext,jdbcType=VARCHAR}");
        }
        
        if (record.getPublishTime() != null) {
            SET("publish_time = #{publishTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAnswerCount() != null) {
            SET("answer_count = #{answerCount,jdbcType=INTEGER}");
        }
        
        if (record.getBrowseCount() != null) {
            SET("browse_count = #{browseCount,jdbcType=INTEGER}");
        }
        
        if (record.getVideoId() != null) {
            SET("video_id = #{videoId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getRightAnswerId() != null) {
            SET("right_answer_id = #{rightAnswerId,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}