package cn.xdl.ovls.entity;

import java.util.Date;

public class PaperExamReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.report_id
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    private Integer reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.user_id
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.paper_id
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.error
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    private Integer error;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.right
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    private Integer right;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.score
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.submit_time
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    private Date submitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.create_time
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.content
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.report_id
     *
     * @return the value of paper_exam_report.report_id
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.report_id
     *
     * @param reportId the value for paper_exam_report.report_id
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.user_id
     *
     * @return the value of paper_exam_report.user_id
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.user_id
     *
     * @param userId the value for paper_exam_report.user_id
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.paper_id
     *
     * @return the value of paper_exam_report.paper_id
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.paper_id
     *
     * @param paperId the value for paper_exam_report.paper_id
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.error
     *
     * @return the value of paper_exam_report.error
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public Integer getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.error
     *
     * @param error the value for paper_exam_report.error
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public void setError(Integer error) {
        this.error = error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.right
     *
     * @return the value of paper_exam_report.right
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public Integer getRight() {
        return right;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.right
     *
     * @param right the value for paper_exam_report.right
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public void setRight(Integer right) {
        this.right = right;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.score
     *
     * @return the value of paper_exam_report.score
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.score
     *
     * @param score the value for paper_exam_report.score
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.submit_time
     *
     * @return the value of paper_exam_report.submit_time
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.submit_time
     *
     * @param submitTime the value for paper_exam_report.submit_time
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.create_time
     *
     * @return the value of paper_exam_report.create_time
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.create_time
     *
     * @param createTime the value for paper_exam_report.create_time
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.content
     *
     * @return the value of paper_exam_report.content
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.content
     *
     * @param content the value for paper_exam_report.content
     *
     * @mbggenerated Sat Nov 03 01:12:24 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}